# Generated by Django 5.1.3 on 2024-11-05 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='main_post_publish_5c5952_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='main_post_publish_cf97d2_idx'),
        ),
    ]
